BEGIN;
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期一', DEFAULT, '花生油', 5, DEFAULT, '花生油', 5, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期一', DEFAULT, '虾皮', 15, DEFAULT, '虾皮', 15, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期一', DEFAULT, '鸡蛋', 55, DEFAULT, '鸡蛋', 55, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期一', '糯米鸡 135g', '糯米', 20, '糯米鸡 135g', '糯米', 20, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期一', '豆沙包 85g', '白糖', 10, '豆沙包 85g', '白糖', 10, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期一', '白粥 250g', '面粉', 60, '白粥 250g', '面粉', 60, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期一', '鸡蛋55g', '大米', 15, '鸡蛋55g', '大米', 15, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期二', DEFAULT, '花生油', 5, DEFAULT, '花生油', 5, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期二', DEFAULT, '虾皮', 15, DEFAULT, '虾皮', 15, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期二', DEFAULT, '鸡蛋', 55, DEFAULT, '鸡蛋', 55, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期二', '糯米鸡 135g', '糯米', 20, '糯米鸡 135g', '糯米', 20, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期二', '豆沙包 85g', '白糖', 10, '豆沙包 85g', '白糖', 10, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期二', '白粥 250g', '面粉', 60, '白粥 250g', '面粉', 60, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期二', '鸡蛋55g', '大米', 15, '鸡蛋55g', '大米', 15, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期三', DEFAULT, '花生油', 5, DEFAULT, '花生油', 5, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期三', DEFAULT, '虾皮', 15, DEFAULT, '虾皮', 15, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期三', DEFAULT, '鸡蛋', 55, DEFAULT, '鸡蛋', 55, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期三', '糯米鸡 135g', '糯米', 20, '糯米鸡 135g', '糯米', 20, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期三', '豆沙包 85g', '白糖', 10, '豆沙包 85g', '白糖', 10, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期三', '白粥 250g', '面粉', 60, '白粥 250g', '面粉', 60, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期三', '鸡蛋55g', '大米', 15, '鸡蛋55g', '大米', 15, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期四', DEFAULT, '花生油', 5, DEFAULT, '花生油', 5, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期四', DEFAULT, '虾皮', 15, DEFAULT, '虾皮', 15, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期四', DEFAULT, '鸡蛋', 55, DEFAULT, '鸡蛋', 55, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期四', '糯米鸡 135g', '糯米', 20, '糯米鸡 135g', '糯米', 20, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期四', '豆沙包 85g', '白糖', 10, '豆沙包 85g', '白糖', 10, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期四', '白粥 250g', '面粉', 60, '白粥 250g', '面粉', 60, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期四', '鸡蛋55g', '大米', 15, '鸡蛋55g', '大米', 15, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期五', DEFAULT, '花生油', 5, DEFAULT, '花生油', 5, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期五', DEFAULT, '虾皮', 15, DEFAULT, '虾皮', 15, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期五', DEFAULT, '鸡蛋', 55, DEFAULT, '鸡蛋', 55, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期五', '糯米鸡 135g', '糯米', 20, '糯米鸡 135g', '糯米', 20, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期五', '豆沙包 85g', '白糖', 10, '豆沙包 85g', '白糖', 10, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期五', '白粥 250g', '面粉', 60, '白粥 250g', '面粉', 60, DEFAULT);
INSERT INTO `dishes_management` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期五', '鸡蛋55g', '大米', 15, '鸡蛋55g', '大米', 15, DEFAULT);
COMMIT;

BEGIN;
INSERT INTO `nutrition_day_analysis` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期一', '在校标准', 580, 18, 580, 'ok!');
INSERT INTO `nutrition_day_analysis` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期一', '在校实给', 580, 18, 580, 'ok!');
INSERT INTO `nutrition_day_analysis` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期一', '在校实给%', 106, 155, 106, 'ok!');
INSERT INTO `nutrition_day_analysis` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期二', '在校标准', 580, 18, 580, 'ok!');
INSERT INTO `nutrition_day_analysis` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期二', '在校实给', 580, 18, 580, 'ok!');
INSERT INTO `nutrition_day_analysis` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期二', '在校实给%', 106, 155, 106, 'ok!');
INSERT INTO `nutrition_day_analysis` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期三', '在校标准', 580, 18, 580, 'ok!');
INSERT INTO `nutrition_day_analysis` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期三', '在校实给', 580, 18, 580, 'ok!');
INSERT INTO `nutrition_day_analysis` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期三', '在校实给%', 106, 155, 106, 'ok!');
INSERT INTO `nutrition_day_analysis` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期四', '在校标准', 580, 18, 580, 'ok!');
INSERT INTO `nutrition_day_analysis` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期四', '在校实给', 580, 18, 580, 'ok!');
INSERT INTO `nutrition_day_analysis` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期四', '在校实给%', 106, 155, 106, 'ok!');
INSERT INTO `nutrition_day_analysis` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期五', '在校标准', 580, 18, 580, 'ok!');
INSERT INTO `nutrition_day_analysis` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期五', '在校实给', 580, 18, 580, 'ok!');
INSERT INTO `nutrition_day_analysis` VALUES (DEFAULT, DEFAULT, DEFAULT, '星期五', '在校实给%', 106, 155, 106, 'ok!');
COMMIT;

BEGIN;
INSERT INTO `nutrition_week_analysis` VALUES (DEFAULT, DEFAULT, DEFAULT, '全日标准', 2326, 2326, 2326, 2326, 2326, 2326, 2326, 2326, 2326, 2326, 2326, 2326, 2326, 2326, 2326, 'ok!');
INSERT INTO `nutrition_week_analysis` VALUES (DEFAULT, DEFAULT, DEFAULT, '在校标准', 558, 558, 558, 558, 558, 558, 558, 558, 558, 558, 558, 558, 558, 558, 558, 'ok!');
INSERT INTO `nutrition_week_analysis` VALUES (DEFAULT, DEFAULT, DEFAULT, '在校实给', 616, 616, 616, 616, 616, 616, 616, 616, 616, 616, 616, 616, 616, 616, 616, 'ok!');
INSERT INTO `nutrition_week_analysis` VALUES (DEFAULT, DEFAULT, DEFAULT, '在校实给%', 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 'ok!');
COMMIT;

BEGIN;
INSERT INTO `comprehensive_data` VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
COMMIT;

BEGIN;
INSERT INTO `dining_ratio` VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
COMMIT;
